Add a description tag to pass AppData validation
Without a description tag in AppData xml file, Flatpak build fails with an error:

```
Processing application org.github.atheriel.snapshot-explorer
org.github.atheriel.snapshot-explorer.desktop: AppData problem: tag-missing : <description> required
Error loading AppData file: AppData file /app/share/appdata/org.github.atheriel.snapshot-explorer.appdata.xml was not valid
Error: ERROR: appstream-compose failed: Child process exited with code 1
```